// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcGjhhiENYAcy6MC8Oen-JqNvneL6KoXk',
    appId: '1:476728969523:web:6231d8065141a09542d646',
    messagingSenderId: '476728969523',
    projectId: 'namma-cambridge',
    authDomain: 'namma-cambridge.firebaseapp.com',
    storageBucket: 'namma-cambridge.firebasestorage.app',
    measurementId: 'G-QK7CWW3TSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV110JsfeW9CxqSfKiDouRk8FhBb3UIEs',
    appId: '1:476728969523:android:4e972128e15228d342d646',
    messagingSenderId: '476728969523',
    projectId: 'namma-cambridge',
    storageBucket: 'namma-cambridge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE7uIPF0UttogyTowZFS103rTAGTmCWpo',
    appId: '1:476728969523:ios:eb685b8d7533cdd642d646',
    messagingSenderId: '476728969523',
    projectId: 'namma-cambridge',
    storageBucket: 'namma-cambridge.firebasestorage.app',
    iosBundleId: 'com.durgaprajapati.nammaCambridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE7uIPF0UttogyTowZFS103rTAGTmCWpo',
    appId: '1:476728969523:ios:eb685b8d7533cdd642d646',
    messagingSenderId: '476728969523',
    projectId: 'namma-cambridge',
    storageBucket: 'namma-cambridge.firebasestorage.app',
    iosBundleId: 'com.durgaprajapati.nammaCambridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcGjhhiENYAcy6MC8Oen-JqNvneL6KoXk',
    appId: '1:476728969523:web:c23c650929f9e86b42d646',
    messagingSenderId: '476728969523',
    projectId: 'namma-cambridge',
    authDomain: 'namma-cambridge.firebaseapp.com',
    storageBucket: 'namma-cambridge.firebasestorage.app',
    measurementId: 'G-FFJEYF6GX6',
  );
}
